@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2NGFkNDQyYzUzZTU3NDIyZGZlYTFlMmQiLCJuYW1lIjoiYm9va2luZyIsInN1YmRvbWFpbiI6ImJvb2tpbmcuc3RvcmVpbm8ud29ybGQifSwidXNlciI6eyJfaWQiOiI2NGFkNDQ4MDUzZTU3NDIyZGZlYTFlOGMiLCJmaXJzdG5hbWUiOiJpbWFuZSIsImxhc3RuYW1lIjoiYm9va2luZyIsImVtYWlsIjoiaW1hbmVpazA5MTBAZ21haWwuY29tIn0sImNvbXBhbnkiOnsic3RhdHVzIjoiVU5DT01QTEVURUQiLCJfaWQiOiI2MDQwYWNlODRlODcyNDA5NTBhN2Q4YzkiLCJuYW1lIjoic3RvcmVpbm8ifSwidG9rZW5JZCI6IjI5OTAyMkdGTEVHUzEwMDAxMlZOWURUQSIsImlhdCI6MTY5MjM3NTQ0NiwiZXhwIjoxNjkzMjM5NDQ2fQ.-3r7vIdUzd4oQm0MNQz7uB-GpWzmQCh5tHudlgnKIsk

###
GET https://admin.storeino.world/stores/api/themes/search?name=METEOR
X-Auth-Token: {{token}}

###
POST https://admin.storeino.world/stores/api/themes/update?name=METEOR
Content-Type: application/json
X-Auth-Token: {{token}}

{
	"config": {
        "schema": {
          "fields": {
            "products": [
              "name",
              "slug",
              "images",
              "price",
              "variants",
              "outStock",
              "type",
              "quantity",
              "tags",
              "collections.name",
              "collections.slug",
              "collections.image",
              "translates"
            ],
            "collections": [
              "name",
              "slug",
              "image",
              "translates",
              "childrens"
            ],
            "images": [
              "src",
              "title"
            ],
            "menus": [],
            "pages": [],
            "brands": []
          },
          "ids": {
            "collections": [
              "64ad4626e81e2618cd1ef08e",
              "64ad45e6e81e2618cd1ef089",
              "64ad45cde81e2618cd1ef084",
              "64ad45a3e81e2618cd1ef07f"
            ],
            "products": [],
            "images": [
              "64d37834ec5efb0054be9eb1",
              "64e13eaabf26a30013381df9",
              "64ad4716e81e2618cd1ef0ad",
              "64ad46d0e81e2618cd1ef0a0"
            ],
            "menus": [
              "64d31236ec5efb0054be9e18"
            ],
            "pages": [],
            "brands": []
          }
        },
        "settings": {
          "tabs": [
            {
              "name": "global",
              "sections": [
                {
                  "name": "header",
                  "icon": "select_all",
                  "blocks": [
                    {
                      "name": "logo",
                      "values": [
                        {
                          "name": "new value",
                          "note": "",
                          "path": "header.logo",
                          "type": "tc_image",
                          "translatable": false,
                          "value": "64d37834ec5efb0054be9eb1"
                        }
                      ]
                    },
                    {
                      "name": "menu",
                      "values": [
                        {
                          "name": "new value",
                          "note": "",
                          "path": "header.menu",
                          "type": "tc_menu",
                          "translatable": false,
                          "value": "64d31236ec5efb0054be9e18"
                        }
                      ]
                    },
                    {
                      "name": "background-image",
                      "values": [
                        {
                          "name": "new value",
                          "note": "",
                          "path": "header.background",
                          "type": "tc_image",
                          "translatable": false,
                          "value": "64e13eaabf26a30013381df9",
                          "notes": "setting the header's background image"
                        }
                      ]
                    },
                    {
                      "name": "content",
                      "values": [
                        {
                          "name": "main heading",
                          "note": "",
                          "path": "header.content.mainheading",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "Discover Flexibility and Convenience: Reserve Your Co-Working Space Today",
                          "inputType": "number"
                        },
                        {
                          "name": "sub heading",
                          "note": "",
                          "path": "header.content.subheading",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "Elevate Your Work Environment with Hassle-Free Co-Working Space Reservations",
                          "inputType": "number"
                        },
                        {
                          "name": "third heading",
                          "note": "",
                          "path": "header.content.thirdheading",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "WELCOME TO METEOR",
                          "inputType": "number"
                        }
                      ]
                    }
                  ]
                },
                {
                  "name": "home",
                  "icon": "select_all",
                  "blocks": [
                    {
                      "name": "items[0]",
                      "values": [
                        {
                          "name": "banner_image",
                          "path": "home.banner.item_0.image",
                          "type": "tc_image",
                          "value": "64ad4716e81e2618cd1ef0ad"
                        },
                        {
                          "name": "new value",
                          "note": "",
                          "path": "home.banner.item_00.image",
                          "type": "tc_image",
                          "translatable": false,
                          "value": "64ad46d0e81e2618cd1ef0a0"
                        }
                      ]
                    }
                  ],
                  "pushable": true,
                  "default": {
                    "name": "items[9]",
                    "values": [
                      {
                        "name": "banner_image",
                        "path": "home.banner.item_9.image",
                        "type": "tc_image",
                        "value": null
                      },
                      {
                        "name": "new value",
                        "note": "",
                        "path": "home.banner.item_10.image",
                        "type": "tc_image",
                        "translatable": false,
                        "value": null
                      }
                    ]
                  }
                },
                {
                  "name": "sections",
                  "icon": "select_all",
                  "blocks": [
                    {
                      "name": "posts",
                      "values": [
                        {
                          "name": "title",
                          "note": "",
                          "path": "sections.posts.title",
                          "type": "tc_input",
                          "translatable": false,
                          "value": " Latest Articles From METEOR "
                        }
                      ]
                    },
                    {
                      "name": "collections",
                      "values": [
                        {
                          "name": "select collection menu",
                          "note": "",
                          "path": "sections.collections",
                          "type": "tc_collection",
                          "value": [
                            "64ad4626e81e2618cd1ef08e",
                            "64ad45e6e81e2618cd1ef089",
                            "64ad45cde81e2618cd1ef084",
                            "64ad45a3e81e2618cd1ef07f"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "locations",
                      "values": [
                        {
                          "name": "select location",
                          "note": "",
                          "path": "sections.locations",
                          "type": "tc_collections",
                          "value": [
                           
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "name": "stats",
                  "icon": "select_all",
                  "blocks": [
                    {
                      "name": "first stat",
                      "values": [
                        {
                          "name": "stat text",
                          "note": "",
                          "path": "stats.firststat.text",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "Active members"
                        },
                        {
                          "name": "stat number",
                          "note": "",
                          "path": "stats.firststat.number",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "100",
                          "inputType": "number"
                        }
                      ]
                    },
                    {
                      "name": "second stat",
                      "values": [
                        {
                          "name": "stat text",
                          "note": "",
                          "path": "stats.secondstat.text",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "Available spaces"
                        },
                        {
                          "name": "stat number",
                          "note": "",
                          "path": "stats.secondstat.number",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "20",
                          "inputType": "number"
                        }
                      ]
                    },
                    {
                      "name": "third stat",
                      "values": [
                        {
                          "name": "stat text",
                          "note": "",
                          "path": "stats.thirdstat.text",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "Positive reviews"
                        },
                        {
                          "name": "stat number",
                          "note": "",
                          "path": "stats.thirdstat.number",
                          "type": "tc_input",
                          "translatable": false,
                          "value": "10",
                          "inputType": "number"
                        }
                      ]
                    }
                  ],
                  "pushable": true,
                  "default": {
                    "name": "items[9]",
                    "values": []
                  }
                }
              ]
            }
          ],
          "currentLang": null
        },
        "current": {
          "translates": [
            {
              "language": "FR",
              "properties": []
            },
            {
              "language": "AR",
              "properties": []
            }
          ],
          "header": {
            "logo": "64d37834ec5efb0054be9eb1",
            "menu": "64d31236ec5efb0054be9e18",
            "background": "64e13eaabf26a30013381df9",
            "content": {
              "mainheading": "Discover Flexibility and Convenience: Reserve Your Co-Working Space Today",
              "subheading": "Elevate Your Work Environment with Hassle-Free Co-Working Space Reservations",
              "thirdheading": "WELCOME TO METEOR"
            }
          },
          "home": {
            "banner": {
              "item_0": {
                "image": "64ad4716e81e2618cd1ef0ad"
              },
              "item_00": {
                "image": "64ad46d0e81e2618cd1ef0a0"
              }
            }
          },
          "sections": {
            "posts": {
              "title": " Latest Articles From METEOR "
            },
            "collections": [
              "64ad4626e81e2618cd1ef08e",
              "64ad45e6e81e2618cd1ef089",
              "64ad45cde81e2618cd1ef084",
              "64ad45a3e81e2618cd1ef07f"
            ],
            "locations": [
                
            ]
          },
          "stats": {
            "firststat": {
              "text": "Active members",
              "number": "100"
            },
            "secondstat": {
              "text": "Available spaces",
              "number": "20"
            },
            "thirdstat": {
              "text": "Positive reviews",
              "number": "10"
            }
          }
        }
      }
}
