@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0YWQ0NDgwNTNlNTc0MjJkZmVhMWU4YyIsImZpcnN0bmFtZSI6ImltYW5lIiwibGFzdG5hbWUiOiJib29raW5nIiwicG9zaXRpb24iOiJDTElFTlQiLCJlbWFpbCI6ImltYW5laWswOTEwQGdtYWlsLmNvbSIsImFkZHJlc3MiOm51bGx9LCJjb21wYW55Ijp7Il9pZCI6IjYwNDBhY2U4NGU4NzI0MDk1MGE3ZDhjOSIsIm5hbWUiOiJzdG9yZWlubyIsInN0YXR1cyI6IlVOQ09NUExFVEVEIn0sInN0b3JlIjp7Il9pZCI6IjY0YWQ0NDJjNTNlNTc0MjJkZmVhMWUyZCIsIm5hbWUiOiJib29raW5nIiwic3ViZG9tYWluIjoiYm9va2luZy5zdG9yZWluby53b3JsZCJ9LCJ0b2tlbklkIjoiNTI3MzcyRVNWUFhRNTMzMjI1TExSSkZZIiwiaWF0IjoxNjk1NjYxNzc2LCJleHAiOjE2OTY1MjU3NzZ9.rIGPuzHtHNZWAPL6itut9rHYb7iTsGYCMhFRElJVwt0

###
GET https://admin.storeino.world/stores/api/themes/search?name=METEOR
X-Auth-Token: {{token}}


###
POST https://admin.storeino.world/stores/api/themes/update?name=METEOR
Content-Type: application/json
X-Auth-Token: {{token}}

